# Generated by Django 5.1.6 on 2025-02-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=100)),
                ('trip_date', models.DateField()),
                ('trip_time', models.TimeField()),
                ('trip_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_description', models.TextField()),
                ('trip_location', models.CharField(max_length=100)),
            ],
        ),
    ]
