# Generated by Django 5.1.6 on 2025-02-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('e_fname', models.CharField(max_length=100)),
                ('e_lname', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('doj', models.DateField()),
            ],
        ),
    ]
