# Generated by Django 5.1.6 on 2025-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField(max_length=10, unique=True)),
                ('prod_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
    ]
